version: "3"
services:
  client:
    image: "snowd3n/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "snowd3n/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
    - REDIS_HOST=$REDIS_HOST
    - REDIS_PORT=$REDIS_PORT
    - PGUSER=$PGUSER
    - PGHOST=$PGHOST
    - PGDATABASE=$PGDATABASE
    - PGPASSWORD=$PGPASSWORD
    - PGPORT=$PGPORT
  worker:
    image: "snowd3n/multi-worker"
    mem_limit: 128m
    hostname: worker
  worker:
    image: "snowd3n/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
    - REDIS_HOST=$REDIS_HOST
    - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "snowd3n/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
